pcv / Pipeline OpenCV (PipelineCv): Element-wise Arithmetic Operations
Element-wise Arithmetic Operations
Functions for performing element-wise mathematical operations between two cv::Mats.
Functions
auto pcv::add (const cv::Mat &other, const cv::Scalar &alpha=cv::Scalar(1.0), const cv::Scalar &beta=cv::Scalar(1.0), const cv::Scalar &gamma=cv::Scalar(0.0))
Weighted sum: alpha * in + beta * other + gamma.
auto pcv::divide (const cv::Mat &other, double scale=1.0)
Element-wise division with optional scale.
auto pcv::multiply (const cv::Mat &other, double scale=1.0)
Element-wise multiplication with optional scale.
auto pcv::subtract (const cv::Mat &other, double scale=1.0)
Element-wise subtraction: in - other, with optional scaling.
Detailed Description
Functions for performing element-wise mathematical operations between two cv::Mats.
Function Documentation
add()
auto pcv::add (const cv::Mat & other, const cv::Scalar & alpha = cv::Scalar(1.0), const cv::Scalar & beta = cv::Scalar(1.0), const cv::Scalar & gamma = cv::Scalar(0.0)) inline
Weighted sum: alpha * in + beta * other + gamma.
Uses cv::addWeighted on the first element of each Scalar.
Parameters
other Second image (same size and type).
alpha Weight for in (default 1.0).
beta Weight for other (default 1.0).
gamma Scalar bias term (default 0.0).
Returns
Callable performing the weighted sum.
Definition at line 348 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::addWeighted(in, alpha[0], other, beta[0], gamma[0], out);
     return out;
   };
 }
Referenced by pcv::add_scalar().
divide()
auto pcv::divide (const cv::Mat & other, double scale = 1.0) inline
Element-wise division with optional scale.
Parameters
other Denominator image.
scale Optional multiplicative factor (default 1.0).
Returns
Callable performing the division in ./ other * scale.
Definition at line 402 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::divide(in, other, out, scale);
     return out;
   };
 }
multiply()
auto pcv::multiply (const cv::Mat & other, double scale = 1.0) inline
Element-wise multiplication with optional scale.
Parameters
other Image to multiply with.
scale Optional multiplicative factor (default 1.0).
Returns
Callable performing the multiplication in .* other * scale.
Definition at line 385 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::multiply(in, other, out, scale);
     return out;
   };
 }
Referenced by pcv::power_spectrum().
subtract()
auto pcv::subtract (const cv::Mat & other, double scale = 1.0) inline
Element-wise subtraction: in - other, with optional scaling.
Parameters
other Image to subtract.
scale Optional multiplicative scale applied after subtraction.
Returns
Callable performing the subtraction.
Definition at line 367 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::subtract(in, other, out, cv::noArray(), in.type());
     if (scale != 1.0) out *= scale;
     return out;
   };
 }
Referenced by pcv::phase(), and pcv::subtract_scalar().