pcv / Pipeline OpenCV (PipelineCv): Complex-Domain Operations
Complex-Domain Operations
Functions for performing element-wise complex-domain operations.
Functions
auto pcv::complex_divide (const cv::Mat &other, double epsilon=1e-12)
Complex division of two 2-channel images with epsilon stabilization.
auto pcv::complex_multiply (const cv::Mat &other)
Complex multiplication of two 2-channel images.
auto pcv::conjugate ()
Complex conjugate of a 2-channel image.
auto pcv::magnitude ()
Magnitude of a 2-channel complex image: sqrt(real^2 + imag^2).
auto pcv::phase (bool degrees=false)
Phase/angle of a 2-channel complex image in (-π, π].
auto pcv::power_spectrum (bool log_scale=true, double epsilon=1e-12)
Power spectrum |F|^2 for complex images, optionally log scaled.
Detailed Description
Functions for performing element-wise complex-domain operations.
Function Documentation
complex_divide()
auto pcv::complex_divide (const cv::Mat & other, double epsilon = 1e-12) inline
Complex division of two 2-channel images with epsilon stabilization.
Computes (a+ib) / (c+id) using (ac+bd)/(c^2+d^2+epsilon) for the real part and (bc-ad)/(c^2+d^2+epsilon) for the imaginary part of the quotient.
Parameters
other Complex denominator with 2 channels.
epsilon Small value added to denominator to avoid division by zero.
Returns
Callable producing complex quotient.
Precondition
Both inputs must have 2 channels.
Definition at line 716 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 2 && other.channels() == 2);
     std::vector<cv::Mat> a(2), b(2), result(2);
     cv::split(in, a);
     cv::split(other, b);
     cv::Mat denominator = b[0].mul(b[0]) + b[1].mul(b[1]) + epsilon;
     result[0] = (a[0].mul(b[0]) + a[1].mul(b[1])) / denominator;  // real
     result[1] = (a[1].mul(b[0]) - a[0].mul(b[1])) / denominator;  // imag
     cv::Mat out;
     cv::merge(result, out);
     return out;
   };
 }
complex_multiply()
auto pcv::complex_multiply (const cv::Mat & other) inline
Complex multiplication of two 2-channel images.
Computes (a+ib) * (c+id) channel-wise.
Parameters
other Complex image with 2 channels.
Returns
Callable producing complex product.
Precondition
Both inputs must have 2 channels.
Definition at line 688 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 2 && other.channels() == 2);
     std::vector<cv::Mat> a(2), b(2), result(2);
     cv::split(in, a);
     cv::split(other, b);
     result[0] = a[0].mul(b[0]) - a[1].mul(b[1]);  // real
     result[1] = a[0].mul(b[1]) + a[1].mul(b[0]);  // imag
     cv::Mat out;
     cv::merge(result, out);
     return out;
   };
 }
conjugate()
auto pcv::conjugate () inline
Complex conjugate of a 2-channel image.
Precondition
in.channels() == 2.
Returns
Callable negating the imaginary channel.
Definition at line 587 of file PipelineCv.h.
{
   return [](const cv::Mat& in) {
     CV_Assert(in.channels() == 2);
     std::vector<cv::Mat> ch(2);
     cv::split(in, ch);
     ch[1] = -ch[1];
     cv::Mat out;
     cv::merge(ch, out);
     return out;
   };
 }
magnitude()
auto pcv::magnitude () inline
Magnitude of a 2-channel complex image: sqrt(real^2 + imag^2).
Returns
Callable producing single-channel magnitude.
Precondition
in.channels() == 2.
Definition at line 608 of file PipelineCv.h.
{
   return [](const cv::Mat& in) {
     CV_Assert(in.channels() == 2);
     std::vector<cv::Mat> p(2);
     cv::split(in, p);
     cv::Mat out;
     cv::magnitude(p[0], p[1], out);
     return out;
   };
 }
phase()
auto pcv::phase (bool degrees = false) inline
Phase/angle of a 2-channel complex image in (-π, π].
Uses cv::phase then wraps to the symmetric interval by subtracting one full period where needed.
Parameters
degrees If true, output is in degrees; otherwise radians.
Returns
Callable producing phase image.
Precondition
in.channels() == 2.
Definition at line 632 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 2);
     std::vector<cv::Mat> p(2);
     cv::split(in, p);
     cv::Mat out;
     cv::phase(p[0], p[1], out, degrees);
     const double half = degrees ? 180.0 : CV_PI;
     const double period = degrees ? 360.0 : 2.0 * CV_PI;
     cv::Mat mask = (out >= half);
     cv::subtract(out, period, out, mask);
     return out;
   };
 }
References pcv::subtract().
power_spectrum()
auto pcv::power_spectrum (bool log_scale = true, double epsilon = 1e-12) inline
Power spectrum |F|^2 for complex images, optionally log scaled.
Parameters
log_scale If true, returns log(|F|^2 + epsilon).
epsilon Stabilizer inside the log (default 1e-12).
Returns
Callable producing single-channel power spectrum image.
Precondition
in.channels() == 2.
Definition at line 658 of file PipelineCv.h.
{
   // Power spectrum: |F|^2 (log optional)
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 2);
     std::vector<cv::Mat> ch(2);
     cv::split(in, ch);
     cv::Mat out;
     cv::multiply(ch[0], ch[0], out);
     cv::Mat tmp;
     cv::multiply(ch[1], ch[1], tmp);
     out += tmp;
     if (log_scale) {
       cv::log(out + epsilon, out);
     }
     return out;
   };
 }
References pcv::log(), and pcv::multiply().