pcv / Pipeline OpenCV (PipelineCv): Scalar/Value Transforms
Scalar/Value Transforms
Functions for scalar/value transformations and per-pixel value operations.
Functions
auto pcv::add_scalar (const cv::Scalar &value)
Add a scalar value to all pixels.
auto pcv::clamp (double minVal=0.0, double maxVal=1.0, bool preserve_type=true)
Clamp pixel values to [minVal, maxVal], with optional type preservation.
auto pcv::divide_scalar (double scale)
Divide all pixels by a scalar.
auto pcv::histogram_equalize_stretch (bool per_channel=true)
Histogram equalization for contrast enhancement.
auto pcv::linear_contrast_stretch (float lower_percent=2.0f, float upper_percent=98.0f, bool per_channel=true)
Contrast stretch using histogram percentiles.
auto pcv::log ()
Natural logarithm of (in + 1).
auto pcv::multiply_scalar (double scale)
Multiply all pixels by a scalar.
auto pcv::normalize (double a=0.0, double b=1.0, int normType=cv::NORM_MINMAX, int dtype=-1)
Normalize with OpenCV's cv::normalize.
auto pcv::subtract_scalar (const cv::Scalar &value)
Subtract a scalar value from all pixels.
Detailed Description
Functions for scalar/value transformations and per-pixel value operations.
Function Documentation
add_scalar()
auto pcv::add_scalar (const cv::Scalar & value) inline
Add a scalar value to all pixels.
Parameters
value Scalar to add (broadcast across channels).
Returns
Callable performing in + value.
Definition at line 236 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::add(in, value, out);
     return out;
   };
 }
References pcv::add().
clamp()
auto pcv::clamp (double minVal = 0.0, double maxVal = 1.0, bool preserve_type = true) inline
Clamp pixel values to [minVal, maxVal], with optional type preservation.
For integer-depth inputs, temporary conversion to CV_32F is used unless preserve_type is false; result is converted back to original type.
Parameters
minVal Lower clamp bound (inclusive).
maxVal Upper clamp bound (inclusive).
preserve_type Preserve original depth via temporary float (default true).
Returns
Callable performing clamping.
Definition at line 275 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::Mat tmp;
     if (preserve_type &&
         (in.depth() == CV_8U || in.depth() == CV_16U || in.depth() == CV_16S))
       in.convertTo(tmp, CV_32F);
     else
       tmp = in;
     cv::min(cv::max(tmp, minVal), maxVal, out);
     if (preserve_type && tmp.type() != in.type()) out.convertTo(out, in.type());
     return out;
   };
 }
divide_scalar()
auto pcv::divide_scalar (double scale) inline
Divide all pixels by a scalar.
Parameters
scale Divisor (must be non-zero).
Returns
Callable performing in / scale.
Definition at line 219 of file PipelineCv.h.
{
   CV_Assert(scale != 0.0);
   return [=](const cv::Mat& in) {
     cv::Mat out;
     in.convertTo(out, in.type(), 1.0 / scale);
     return out;
   };
 }
histogram_equalize_stretch()
auto pcv::histogram_equalize_stretch (bool per_channel = true) inline
Histogram equalization for contrast enhancement.
Works on grayscale or color images (3-channel). For color inputs, performs per-channel equalization or luminance-based equalization in YCrCb space.
Supports CV_8U, CV_16U, and CV_32F inputs. Output retains same type/depth. For float data, values are assumed in [0, 1] and scaled to 8-bit internally.
Parameters
per_channel Apply equalization independently to each channel (default is true).
Returns
Callable that performs histogram equalization.
Definition at line 441 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 1 || in.channels() == 3);
     CV_Assert(in.depth() == CV_8U || in.depth() == CV_16U ||
               in.depth() == CV_32F);
     auto equalize_single_channel = [](const cv::Mat& ch) -> cv::Mat {
       cv::Mat ch8u, eq;
       if (ch.depth() == CV_8U)
         ch8u = ch;
       else if (ch.depth() == CV_16U)
         ch.convertTo(ch8u, CV_8U, 1.0 / 256.0);  // scale 16U → 8U
       else if (ch.depth() == CV_32F)
         ch.convertTo(ch8u, CV_8U, 255.0);  // assume [0,1] float
       cv::equalizeHist(ch8u, eq);
       // Convert back to original type
       cv::Mat out;
       if (ch.depth() == CV_8U)
         out = eq;
       else if (ch.depth() == CV_16U)
         eq.convertTo(out, CV_16U, 256.0);  // scale 8U → 16U
       else if (ch.depth() == CV_32F)
         eq.convertTo(out, CV_32F, 1.0 / 255.0);  // scale 8U → float
       return out;
     };
     // Grayscale
     if (in.channels() == 1) return equalize_single_channel(in);
     // Color (3-channel)
     std::vector<cv::Mat> ch;
     cv::split(in, ch);
     if (per_channel) {
       for (auto& c : ch) c = equalize_single_channel(c);
       cv::Mat out;
       cv::merge(ch, out);
       return out;
     } else {
       // Luminance equalization in YCrCb space
       cv::Mat ycrcb, eq_ycrcb;
       cv::cvtColor(in, ycrcb, cv::COLOR_BGR2YCrCb);
       std::vector<cv::Mat> ych;
       cv::split(ycrcb, ych);
       ych[0] = equalize_single_channel(ych[0]);  // equalize Y only
       cv::merge(ych, eq_ycrcb);
       cv::Mat out;
       cv::cvtColor(eq_ycrcb, out, cv::COLOR_YCrCb2BGR);
       return out;
     }
   };
 }
linear_contrast_stretch()
auto pcv::linear_contrast_stretch (float lower_percent = 2.0f, float upper_percent = 98.0f, bool per_channel = true) inline
Contrast stretch using histogram percentiles.
Linearly maps intensities so that lower_percent of values are clipped to black and upper_percent to white. Works on grayscale or color images, supporting 8U, 16U, and 32F depths.
Parameters
lower_percent Lower tail cutoff (percentage)
upper_percent Upper tail cutoff (percentage)
per_channel Stretch each channel independently (else luminance-based)
Returns
Callable performing contrast stretch.
Definition at line 345 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     CV_Assert(in.channels() == 1 || in.channels() == 3);
     CV_Assert(in.depth() == CV_8U || in.depth() == CV_16U ||
               in.depth() == CV_32F);
     const int bins = (in.depth() == CV_8U)    ? 256
                      : (in.depth() == CV_16U) ? 65536
                                               : 65536;
     const float range[] = {0.0f, static_cast<float>(bins)};
     const float* histRange = {range};
     auto stretch_channel = [&](const cv::Mat& ch) {
       cv::Mat hist;
       cv::calcHist(&ch, 1, 0, cv::Mat(), hist, 1, &bins, &histRange, true,
                    false);
       std::vector<float> cdf(bins);
       cdf[0] = hist.at<float>(0);
       for (int i = 1; i < bins; ++i) cdf[i] = cdf[i - 1] + hist.at<float>(i);
       float total = cdf.back();
       float lo_thresh = lower_percent / 100.0f * total;
       float hi_thresh = upper_percent / 100.0f * total;
       int lo = 0, hi = bins - 1;
       for (int i = 0; i < bins; ++i)
         if (cdf[i] >= lo_thresh) {
           lo = i;
           break;
         }
       for (int i = bins - 1; i >= 0; --i)
         if (cdf[i] <= hi_thresh) {
           hi = i;
           break;
         }
       cv::Mat out;
       if (in.depth() == CV_32F) {
         out = (ch - float(lo)) / float(hi - lo);
         cv::min(cv::max(out, 0.0f), 1.0f, out);
       } else {
         double scale = (hi == lo) ? 1.0 : double(bins - 1) / (hi - lo);
         ch.convertTo(out, ch.type(), scale, -lo * scale);
         cv::threshold(out, out, bins - 1, bins - 1, cv::THRESH_TRUNC);
         cv::threshold(out, out, 0, 0, cv::THRESH_TOZERO);
       }
       return out;
     };
     if (in.channels() == 1) return stretch_channel(in);
     std::vector<cv::Mat> ch;
     cv::split(in, ch);
     if (per_channel) {
       for (auto& c : ch) c = stretch_channel(c);
     } else {
       // Luminance approach
       cv::Mat lum;
       cv::cvtColor(in, lum, cv::COLOR_BGR2GRAY);
       cv::Mat stretch_lum = stretch_channel(lum);
       std::vector<cv::Mat> ch_f(3);
       for (int i = 0; i < 3; ++i) ch[i].convertTo(ch_f[i], CV_32F);
       cv::Mat lum_f, stretch_f;
       lum.convertTo(lum_f, CV_32F);
       stretch_lum.convertTo(stretch_f, CV_32F);
       cv::Mat ratio = stretch_f / (lum_f + 1e-6f);
       for (int i = 0; i < 3; ++i) ch_f[i] = ch_f[i].mul(ratio);
       for (int i = 0; i < 3; ++i) ch_f[i].convertTo(ch[i], in.depth());
     }
     cv::Mat out;
     cv::merge(ch, out);
     return out;
   };
 }
log()
auto pcv::log () inline
Natural logarithm of (in + 1).
Useful for simple log compression while avoiding log(0).
Returns
Callable computing log(in + 1).
Definition at line 300 of file PipelineCv.h.
                   {
   return [](const cv::Mat& in) {
     cv::Mat out;
     cv::log(in + 1.0, out);
     return out;
   };
 }
Referenced by pcv::power_spectrum().
multiply_scalar()
auto pcv::multiply_scalar (double scale) inline
Multiply all pixels by a scalar.
Parameters
scale Multiplicative factor.
Returns
Callable performing in * scale.
Definition at line 203 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     in.convertTo(out, in.type(), scale);
     return out;
   };
 }
normalize()
auto pcv::normalize (double a = 0.0, double b = 1.0, int normType = cv::NORM_MINMAX, int dtype = -1) inline
Normalize with OpenCV's cv::normalize.
Default is min-max scaling to [a,b]. See OpenCV docs for normType/dtype.
Parameters
a Lower bound (default 0.0).
b Upper bound (default 1.0).
normType Normalization type (default cv::NORM_MINMAX).
dtype Output type (default -1 = same type as input).
Returns
Callable performing normalization.
Definition at line 321 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::normalize(in, out, a, b, normType, dtype);
     return out;
   };
 }
subtract_scalar()
auto pcv::subtract_scalar (const cv::Scalar & value) inline
Subtract a scalar value from all pixels.
Parameters
value Scalar to subtract (broadcast across channels).
Returns
Callable performing in - value.
Definition at line 252 of file PipelineCv.h.
{
   return [=](const cv::Mat& in) {
     cv::Mat out;
     cv::subtract(in, value, out);
     return out;
   };
 }
References pcv::subtract().